import { describe, expect, it } from "vitest";
import { EMPTY_WIZARD_STATE, SAMPLE_PROFILE } from "../../data";
import {
  decisionInputSchema,
  ENRICHMENT_BOUNDS,
  findUnsupportedNumericClaims,
  intelligenceEnrichmentSchema,
  validateEvidenceReferences,
} from "../schema";

function validEnrichment() {
  return {
    currentSituation: "Situation summary.",
    businessOutcomes: "Outcome summary.",
    decisionDrivers: ["Modernization"],
    recommendationNarrative: "Platform A fits best.",
    alternativeNarrative: "Platform B is close behind.",
    keyTradeOffs: ["Platform B is stronger on cost."],
    risksNarrative: "Validate the commercial model.",
    opportunitiesNarrative: "Opens up governed data products.",
    assumptionsNarrative: "Assumes stated inputs are complete.",
    missingInformation: [],
    validationQuestions: ["Has budget been confirmed?"],
    challengeQuestions: ["What would make Platform B the better pick?"],
    suggestedNextStepsNarrative: "[now] Validate with stakeholders.",
    suggestedWorkshopsNarrative: "Architecture deep dive: a 2-hour session.",
    executiveSummary: "Platform A is recommended.",
    confidenceExplanation: "Confidence reflects complete inputs.",
    evidenceReferences: ["platform-a"],
    disclosure: "Generated by deterministic templates.",
  };
}

describe("intelligenceEnrichmentSchema", () => {
  it("accepts a valid enrichment", () => {
    const result = intelligenceEnrichmentSchema.safeParse(validEnrichment());
    expect(result.success).toBe(true);
  });

  it("rejects a missing required field", () => {
    const withoutDisclosure: Partial<ReturnType<typeof validEnrichment>> = validEnrichment();
    delete withoutDisclosure.disclosure;
    const result = intelligenceEnrichmentSchema.safeParse(withoutDisclosure);
    expect(result.success).toBe(false);
  });

  it("rejects text exceeding its declared bound", () => {
    const oversized = { ...validEnrichment(), currentSituation: "a".repeat(ENRICHMENT_BOUNDS.currentSituation + 1) };
    const result = intelligenceEnrichmentSchema.safeParse(oversized);
    expect(result.success).toBe(false);
  });

  it("rejects an array exceeding its declared max item count", () => {
    const tooMany = { ...validEnrichment(), keyTradeOffs: Array.from({ length: 10 }, (_, i) => `trade-off ${i}`) };
    const result = intelligenceEnrichmentSchema.safeParse(tooMany);
    expect(result.success).toBe(false);
  });

  it("rejects an unknown/extra field — e.g. an attempted numeric score override", () => {
    const withScore = { ...validEnrichment(), donnaScore: 99 };
    const result = intelligenceEnrichmentSchema.safeParse(withScore);
    expect(result.success).toBe(false);
  });
});

describe("validateEvidenceReferences", () => {
  it("accepts references that exist in the known set", () => {
    const result = validateEvidenceReferences(["a", "b"], new Set(["a", "b", "c"]));
    expect(result.valid).toBe(true);
  });

  it("rejects references to unknown ids", () => {
    const result = validateEvidenceReferences(["a", "z"], new Set(["a", "b"]));
    expect(result).toEqual({ valid: false, unknownIds: ["z"] });
  });
});

describe("findUnsupportedNumericClaims", () => {
  it("finds no issue when every percentage matches a known score", () => {
    const claims = findUnsupportedNumericClaims(
      {
        recommendationNarrative: "Platform A scored 91%.",
        alternativeNarrative: "Platform B scored 84%.",
        executiveSummary: "Overall confidence is 78%.",
      },
      new Set([91, 84, 78]),
    );
    expect(claims).toEqual([]);
  });

  it("flags a percentage that matches no known score — a fabricated score attempt", () => {
    const claims = findUnsupportedNumericClaims(
      {
        recommendationNarrative: "Platform A scored 97%.",
        alternativeNarrative: "",
        executiveSummary: "",
      },
      new Set([91, 84, 78]),
    );
    expect(claims.length).toBeGreaterThan(0);
    expect(claims[0]).toContain("97%");
  });
});

describe("decisionInputSchema", () => {
  it("accepts the product's own sample wizard state", () => {
    const result = decisionInputSchema.safeParse({ wizardState: SAMPLE_PROFILE });
    expect(result.success).toBe(true);
  });

  it("accepts the empty wizard state", () => {
    const result = decisionInputSchema.safeParse({ wizardState: EMPTY_WIZARD_STATE });
    expect(result.success).toBe(true);
  });

  it("accepts a long-but-reasonable note (graceful degradation, not rejection)", () => {
    const state = { ...SAMPLE_PROFILE, company: { ...SAMPLE_PROFILE.company, note: "a".repeat(5000) } };
    const result = decisionInputSchema.safeParse({ wizardState: state });
    expect(result.success).toBe(true);
  });

  it("rejects a pathologically oversized note", () => {
    const state = { ...SAMPLE_PROFILE, company: { ...SAMPLE_PROFILE.company, note: "a".repeat(50_000) } };
    const result = decisionInputSchema.safeParse({ wizardState: state });
    expect(result.success).toBe(false);
  });
});
