/**
 * The default, always-available IntelligenceProvider. Transforms an
 * EvidencePackage into IntelligenceEnrichment using deterministic
 * templates — no network call, no API key, no external service. This is
 * what Phase 5.1 ships as the only real provider, and what every
 * environment without a configured external provider falls back to. See
 * docs/intelligence/provider-boundaries.md.
 *
 * Every sentence this module writes is assembled from strings and
 * numbers already present in the EvidencePackage it's given — it never
 * invents a fact, a number, or a claim. That's not a stylistic choice;
 * it's the reason this provider's `enrich()` can never fail validation
 * for an unsupported claim (see schema.ts) by construction.
 */
import type { IntelligenceProvider } from "../provider";
import { ENRICHMENT_BOUNDS } from "../schema";
import type { EvidencePackage, IntelligenceEnrichment, IntelligenceRequest, IntelligenceResult } from "../types";

/** Guarantees every field this provider returns fits the same bounds
 * schema.ts validates against — this provider must never fail its own
 * enrichment's validation because a template produced one sentence too
 * many. */
function cap(text: string, max: number): string {
  return text.length <= max ? text : `${text.slice(0, max - 1).trimEnd()}…`;
}

function capList(items: string[], maxItems: number, maxLen: number): string[] {
  return items.slice(0, maxItems).map((item) => cap(item, maxLen));
}

const DISCLOSURE =
  "Generated by deterministic templates from Donna's own computed results — no AI model was used, and no score or ranking was affected by this text.";

function joinList(items: string[], conjunction = "and"): string {
  if (items.length === 0) return "";
  if (items.length === 1) return items[0];
  if (items.length === 2) return `${items[0]} ${conjunction} ${items[1]}`;
  return `${items.slice(0, -1).join(", ")}, ${conjunction} ${items[items.length - 1]}`;
}

function buildCurrentSituation(evidence: EvidencePackage): string {
  const { goals, industry, companySize } = evidence.decisionContext;
  const orgPhrase =
    companySize && industry
      ? `a ${companySize.toLowerCase()} ${industry.toLowerCase()} organization`
      : industry
        ? `a ${industry.toLowerCase()} organization`
        : "your organization";
  const goalsPhrase = goals.length > 0 ? `pursuing ${joinList(goals)}` : "without a specific goal selected yet";

  return `This assessment was run for ${orgPhrase}, ${goalsPhrase}. ${evidence.shortlist.length} platform${evidence.shortlist.length === 1 ? " was" : "s were"} evaluated against Donna's deterministic scoring model.`;
}

function buildBusinessOutcomes(evidence: EvidencePackage): string {
  const { goals } = evidence.decisionContext;
  if (goals.length === 0) {
    return "No specific goals were selected, so the outcomes this assessment optimizes for are generic rather than tailored to a stated business objective.";
  }
  return `The selected goals (${joinList(goals)}) point toward measurable outcomes in those areas — the scoring below weights platform fit accordingly.`;
}

function buildRecommendationNarrative(evidence: EvidencePackage): string {
  const primary = evidence.shortlist[0];
  if (!primary) return "No platform could be evaluated from the evidence available.";

  const topEvidence = primary.positiveEvidence.slice(0, 2);
  const evidencePhrase =
    topEvidence.length > 0
      ? ` primarily because ${joinList(topEvidence.map((e) => e.charAt(0).toLowerCase() + e.slice(1)))}`
      : "";

  return `${primary.name} scored highest overall (${primary.overallScore}%)${evidencePhrase}.`;
}

function buildAlternativeNarrative(evidence: EvidencePackage): string {
  const [, alternative] = evidence.shortlist;
  if (!alternative) return "No alternative platform met the threshold to be shown as a distinct option.";

  const strength = alternative.positiveEvidence[0];
  const strengthPhrase = strength ? ` — notably, ${strength.charAt(0).toLowerCase()}${strength.slice(1)}` : "";

  return `${alternative.name} was the closest alternative (${alternative.overallScore}%)${strengthPhrase}.`;
}

function buildKeyTradeOffs(evidence: EvidencePackage): string[] {
  const [primary, alternative] = evidence.shortlist;
  if (!primary || !alternative) return [];

  const tradeOffs: string[] = [];
  for (const altDim of alternative.dimensionScores) {
    const primaryDim = primary.dimensionScores.find((d) => d.key === altDim.key);
    if (primaryDim && altDim.score > primaryDim.score) {
      tradeOffs.push(
        `${alternative.name} scores higher on ${altDim.label} (${altDim.score}% vs ${primaryDim.score}%), while ${primary.name} leads overall.`,
      );
    }
  }

  return tradeOffs.slice(0, 5);
}

function buildValidationQuestions(evidence: EvidencePackage): string[] {
  const questions = [
    "Has this assessment's stated budget and timeline been confirmed with the actual budget owner?",
    "Are the selected goals still the organization's top priority, or have they shifted since this was run?",
  ];
  if (evidence.knownInformationGaps.length > 0) {
    questions.push("Can the flagged information gaps be filled in before this recommendation is finalized?");
  }
  return questions.slice(0, 5);
}

function buildChallengeQuestions(evidence: EvidencePackage): string[] {
  const [primary, alternative] = evidence.shortlist;
  const questions: string[] = [];

  if (primary && alternative) {
    questions.push(`What would have to change for ${alternative.name} to be the better choice instead?`);
  }
  if (primary?.negativeEvidence[0]) {
    questions.push(`How significant is this concern in practice: ${primary.negativeEvidence[0]}`);
  }
  questions.push("Which of the stated constraints is the least flexible, and does the recommendation respect it?");

  return questions.slice(0, 5);
}

function buildConfidenceExplanation(evidence: EvidencePackage): string {
  if (evidence.knownInformationGaps.length === 0) {
    return "Confidence reflects a complete set of inputs and clear scoring signal across the evaluated platforms.";
  }
  return `Confidence is reduced by: ${joinList(evidence.knownInformationGaps.map((g) => g.charAt(0).toLowerCase() + g.slice(1)))}`;
}

function buildEnrichment(evidence: EvidencePackage): IntelligenceEnrichment {
  const b = ENRICHMENT_BOUNDS;

  const risksNarrative =
    evidence.deterministicRisks.length > 0
      ? `Key risks to validate: ${joinList(evidence.deterministicRisks.map((r) => r.charAt(0).toLowerCase() + r.slice(1)))}`
      : "No specific risks were flagged for this combination of inputs.";

  const opportunitiesNarrative =
    evidence.deterministicOpportunities.length > 0
      ? `This path opens up: ${joinList(evidence.deterministicOpportunities.map((o) => o.charAt(0).toLowerCase() + o.slice(1)))}`
      : "No specific opportunities were flagged for this combination of inputs.";

  const assumptionsNarrative =
    evidence.deterministicAssumptions.length > 0
      ? `This assessment assumes: ${joinList(evidence.deterministicAssumptions.map((a) => a.charAt(0).toLowerCase() + a.slice(1)))}`
      : "No explicit assumptions were required beyond the inputs provided.";

  const suggestedNextStepsNarrative =
    evidence.deterministicNextSteps.length > 0
      ? evidence.deterministicNextSteps.map((s) => `[${s.horizon}] ${s.text}`).join(" ")
      : "No specific next steps were generated for this assessment.";

  const suggestedWorkshopsNarrative =
    evidence.deterministicWorkshops.length > 0
      ? evidence.deterministicWorkshops.map((w) => `${w.title}: ${w.description}`).join(" ")
      : "No specific workshops were suggested for this assessment.";

  const executiveSummary = `${buildRecommendationNarrative(evidence)} ${buildBusinessOutcomes(evidence)}`;

  return {
    currentSituation: cap(buildCurrentSituation(evidence), b.currentSituation),
    businessOutcomes: cap(buildBusinessOutcomes(evidence), b.businessOutcomes),
    decisionDrivers: capList(evidence.decisionContext.goals, b.decisionDrivers.maxItems, b.decisionDrivers.maxLen),
    recommendationNarrative: cap(buildRecommendationNarrative(evidence), b.recommendationNarrative),
    alternativeNarrative: cap(buildAlternativeNarrative(evidence), b.alternativeNarrative),
    keyTradeOffs: capList(buildKeyTradeOffs(evidence), b.keyTradeOffs.maxItems, b.keyTradeOffs.maxLen),
    risksNarrative: cap(risksNarrative, b.risksNarrative),
    opportunitiesNarrative: cap(opportunitiesNarrative, b.opportunitiesNarrative),
    assumptionsNarrative: cap(assumptionsNarrative, b.assumptionsNarrative),
    missingInformation: capList(evidence.knownInformationGaps, b.missingInformation.maxItems, b.missingInformation.maxLen),
    validationQuestions: capList(buildValidationQuestions(evidence), b.validationQuestions.maxItems, b.validationQuestions.maxLen),
    challengeQuestions: capList(buildChallengeQuestions(evidence), b.challengeQuestions.maxItems, b.challengeQuestions.maxLen),
    suggestedNextStepsNarrative: cap(suggestedNextStepsNarrative, b.suggestedNextStepsNarrative),
    suggestedWorkshopsNarrative: cap(suggestedWorkshopsNarrative, b.suggestedWorkshopsNarrative),
    executiveSummary: cap(executiveSummary, b.executiveSummary),
    confidenceExplanation: cap(buildConfidenceExplanation(evidence), b.confidenceExplanation),
    evidenceReferences: evidence.shortlist.map((p) => p.id).slice(0, b.evidenceReferences.maxItems),
    disclosure: cap(DISCLOSURE, b.disclosure),
  };
}

export const deterministicIntelligenceProvider: IntelligenceProvider = {
  id: "deterministic-v1",
  model: null,

  async enrich(request: IntelligenceRequest): Promise<IntelligenceResult> {
    if (request.evidence.shortlist.length === 0) {
      return { status: "invalid_output", reason: "Evidence package contained no shortlisted platforms." };
    }

    return { status: "ok", enrichment: buildEnrichment(request.evidence) };
  },
};
